# Generated by Django 4.2.1 on 2023-06-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0002_alter_info_composer_alter_info_lyricist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='thumbnail',
            field=models.URLField(default='https://alcoholproject.blob.core.windows.net/demo/music logo design.png', max_length=500),
        ),
    ]
