# Generated by Django 4.2.1 on 2023-06-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0003_alter_music_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='thumbnail',
            field=models.URLField(default='https://alcoholproject.blob.core.windows.net/demo/music%20logo%20design.png', max_length=500),
        ),
    ]
